services:
  - type: web
    name: freeedit
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /healthz
    autoDeploy: true
    domains:
      - freeedit.srbmaury.com
    envVars:
      - key: MAX_UPLOAD_MB
        value: "100"
      - key: MAX_DURATION_MIN
        value: "10"
      - key: JOB_TTL_HOURS
        value: "1"
